# Generated by Django 3.2.5 on 2021-07-30 07:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Lctl', '0002_auto_20210730_1301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='freelancer',
            old_name='Country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='freelancer',
            old_name='Phn',
            new_name='phn',
        ),
        migrations.RemoveField(
            model_name='freelancer',
            name='is_freelancer',
        ),
        migrations.AddField(
            model_name='freelancer',
            name='username',
            field=models.CharField(default=django.utils.timezone.now, max_length=25),
            preserve_default=False,
        ),
    ]
