# Generated by Django 3.2.5 on 2021-07-30 13:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Lctl', '0003_auto_20210730_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancer',
            name='freelancer_photo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='Lctl/images'),
            preserve_default=False,
        ),
    ]
