# Generated by Django 3.2.5 on 2021-07-30 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lctl', '0004_freelancer_freelancer_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancer',
            name='country',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='freelancer_photo',
            field=models.ImageField(default='', upload_to='Lctl/images'),
        ),
    ]
