# Generated by Django 3.2.5 on 2021-07-31 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lctl', '0005_auto_20210730_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancer',
            name='payperhr',
            field=models.CharField(default='250', max_length=3),
        ),
    ]
