# Generated by Django 3.2.5 on 2021-07-31 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lctl', '0008_alter_freelancer_freelancer_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancer',
            name='aboutdesc',
            field=models.CharField(default='', max_length=2000),
            preserve_default=False,
        ),
    ]
