# Generated by Django 3.2.5 on 2021-08-01 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lctl', '0011_alter_freelancer_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
