# Generated by Django 3.2.5 on 2021-08-01 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lctl', '0012_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.BooleanField(default=False),
        ),
    ]
