# Generated by Django 3.2.5 on 2021-08-02 12:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Lctl', '0013_alter_order_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='client_email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
    ]
