# Generated by Django 3.2.5 on 2021-08-02 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lctl', '0016_alter_freelancer_freelancer_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freelancer',
            name='freelancer_photo',
        ),
    ]
